[project]
name = "e5-lora-config"
version = "0.1.0"
description = "Configures a Seeed Wio Grove E5 LoRaWAN module."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.12.0",
    "pyserial>=3.5",
    "questionary>=2.1.0",
]
